export default function privacypolicy() {
  return (
    <section>
      <div className="flex flex-col justify-center items-center pt-16">
        <div className="mx-auto w-full max-w-7xl text-left flex justify-start items-center mb-10 mt-10">
          <div className="w-fit flex justify-center items-center gap-x-2 cursor-pointer text-sm p-2 rounded-md hover:bg-[#f7f7f5]">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="w-4 h-4"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3"
              ></path>
            </svg>
            Back
          </div>
        </div>
        <h1 className="text-2xl font-bold text-blue-700">Privacy Policy</h1>
        <div className="max-w-screen-lg px-10 my-10">
          <p className="font-bold text-center">
            Thank you for being a part of Prodoc - a product by Growth Hacker
            Consulting Private Limited. <br /> Your privacy is important to us.
          </p>
          <p className="text-center mt-4">
            Please read the following statement to learn about our information
            gathering and dissemination practices.
          </p>
          <p className="mt-20 font-extrabold">SCOPE:</p>
          <p className="mt-3">
            Growth Hacker Consulting Private Limited (hereinafter referred to as
            “the Company”, “we”, “our”, “us”) offers a suite of messaging
            software-as-a-service solutions through a single platform under the
            name and style of “Prodoc - a product by Growth Hacker Consulting
            Private Limited” (hereinafter referred to as “Solution”). The
            Solution helps customers manage communications with their users more
            efficiently. We are committed to protecting your privacy and
            respecting your data.
          </p>
          <p className="mt-3">
            This policy (“Privacy Policy”), together with the terms and
            conditions available at [https:prodoc.ai/privacy-policy], and all
            other policies listed as part of the Solution, outlines our privacy
            practices regarding the collection, use, and safeguarding of your
            information through the Solution and the services offered.
          </p>
          <p className="mt-3">
            By using, registering, or signing up for the Solution, you accept
            the terms of this Privacy Policy. If you do not accept any of these
            terms, your usage of the Solution will be restricted. By clicking
            the “agree” button and submitting personal information (or if you
            are a minor, having your personal information submitted by your
            parents or legal guardian), you accept this Privacy Policy and agree
            to be contacted by us to inform you about products, services, and
            upcoming benefits offered by us or our affiliates.
          </p>
          <p className="mt-3">
            This Privacy Policy is an electronic record under the Information
            Technology Act, 2000 (as amended/re-enacted from time to time) (“IT
            Act”) and rules thereunder. It is published in accordance with Rule
            3 (1) of the Information Technology (Intermediaries Guidelines)
            Rules, 2011, which requires publishing rules and regulations, a
            privacy policy, and terms of use for access or usage of the
            Solution. This Privacy Policy is an electronic record generated by a
            computer system and does not require any physical or digital
            signatures.
          </p>
          <p className="mt-10 font-extrabold">CHANGES TO THE PRIVACY POLICY:</p>
          <p className="mt-3">
            We will treat your information in accordance with applicable laws
            and regulations of India. This Privacy Policy is subject to
            modifications based on business, legal, or regulatory requirements
            and will be updated online from time to time.
          </p>
          <p className="mt-3">
            We will make all efforts to communicate any significant changes to
            this Privacy Policy to you. You are encouraged to periodically visit
            this page to review the Privacy Policy and any changes to it. Your
            continued participation in the Solution after any modifications to
            this Privacy Policy will be deemed as your acceptance of those
            changes.
          </p>
          <p className="mt-10 font-extrabold">PERSONAL INFORMATION WE COLLECT:</p>
          <p className="mt-3">
            “Personal information” refers to information that can be used to
            identify you and may include details such as your name, age, gender,
            contact information, messages, business information, and products or
            services you are interested in. Sensitive personal information will
            be handled in accordance with applicable laws.
          </p>
          <p className="mt-10 font-extrabold">
            How We Collect, Use, and Share Your Personal Information:
          </p>
          <p className="mt-10 font-extrabold">Collection:</p>
          <p className="mt-3">
            We may collect your personal information when it is relevant to
            provide you with services, complete transactions, or provide any
            product you have requested under the Solution. You also consent to
            the collection of certain personal information when applying for
            products or services related to the Solution.
          </p>
          <p className="mt-10 font-extrabold">Usage:</p>
          <p className="mt-3">
            We use your personal information to validate and process your
            requests, assist the Company and its affiliates in handling your
            orders or transactions, communicate details about allied products
            and services, improve the quality of the Solution, help determine
            the services or products best suited for your needs, facilitate our
            internal business operations, comply with legal and regulatory
            requirements, provide recommendations based on your participation,
            send marketing communications, resolve disputes, detect fraud or
            other criminal activity, enforce our terms and conditions, or as
            otherwise described at the time of collection.
          </p>
          <p className="mt-10 font-extrabold">Sharing:</p>
          <p className="mt-3">
            We may share your personal information with our affiliates as
            necessary to provide services on our behalf, display advertising,
            provide search results and links, or deliver customer service. Our
            affiliates may market to you as a result of such sharing. If you
            wish to opt-out of any such sharing, please email us at
            legal@prodoc.io.
          </p>
          <p className="mt-3">
            We may also share your personal information with third parties when
            required to provide services, enhance your experience, or comply
            with legal obligations. We may share your personal information to:
          </p>
          <ul className="mt-2">
            <li>
              (a) Meet any applicable law, regulation, legal process, or
              enforceable governmental request.
            </li>
            <li>
              (b) Detect, prevent, or address fraud, security, or technical
              issues.
            </li>
            <li>
              (c) Protect against harm to the rights, property, or safety of our
              customers or the public, as required or permitted by applicable
              laws in India.
            </li>
          </ul>
          <p className="mt-10 font-extrabold">
            NON-PERSONAL INFORMATION WE COLLECT:
          </p>
          <p className="mt-3">
            Non-personal information refers to any information that does not
            identify you personally. This may include system or hardware
            identifiers, software details, and peripherals. When combined with
            personal information, non-personal information is treated as
            personal information.
          </p>
          <p className="mt-10 font-extrabold">Collection:</p>
          <p className="mt-3">
            We may collect non-personal information to improve the Solution and
            services, provide software updates, product support, and other
            services, and verify compliance with this Privacy Policy. Once
            collected, this information is anonymized so it does not personally
            identify you.
          </p>
          <p className="mt-10 font-extrabold">Usage:</p>
          <p className="mt-3">
            Non-personal information is gathered periodically to provide and
            improve the Solution and services, facilitate the provision of
            updates, support, and verify compliance with this Privacy Policy.
            Since non-personal information does not identify you personally, we
            may use and disclose it at our discretion, subject to applicable
            laws.
          </p>
          <p className="mt-10 font-extrabold">Sharing:</p>
          <p className="mt-3">
            We may share non-personal information with our partners and Third
            Party Service Providers to improve their software, hardware, and
            services that are designed for use with the Solution, as long as the
            information does not personally identify you.
          </p>
          <p className="mt-10 font-extrabold">Cloud API:</p>
          <p className="mt-3">
            The WhatsApp Infrastructure helps communication between users and
            the Prodoc platform. The Client agrees that data shared on the
            WhatsApp infrastructure will reside on Cloud API&#x27;s (&#x27;Data
            Residence&#x27;), a Meta Product. Any Client data previously routed
            and stored on WhatsApp infrastructure will be migrated to data
            centers located in North America and the European Union via Cloud
            API service by Meta.
          </p>
          <p className="mt-3">
            The Company does not offer data localization for any data shared or
            obtained via the WhatsApp messaging services.
          </p>
          <p className="mt-10 font-extrabold">LOCATION SERVICES:</p>
          <p className="mt-3">
            The Solution, its licensees, and agents may access, collect, and
            analyze your participation and usage of the Solution, including
            location data, to improve the Solution&#x27;s design, functionality,
            and content. This data is collected through Bluetooth, Wi-Fi
            signals, and other technologies. Location settings must be enabled
            on your device for this data to be collected.
          </p>
          <p className="mt-3">
            By using the Solution, you agree to the transmission, collection,
            maintenance, processing, and use of your location data to provide
            and improve services.
          </p>
          <p className="mt-10 font-extrabold">COOKIES:</p>
          <p className="mt-3">
            We use both permanent and temporary cookies to collect information
            related to the Solution. Cookies help us improve the Solution and
            services, but do not identify you personally. To the extent that IP
            addresses or similar identifiers are considered personal information
            by law, we treat any linked information as personal information.
          </p>
          <p className="mt-10 font-extrabold">COLLECTION OF OTHER INFORMATION:</p>
          <p className="mt-3">
            The Solution may also collect other information about you as
            described or with your consent. You can choose not to provide
            certain types of information, but this may affect your ability to
            use some services.
          </p>
          <p className="mt-10 font-extrabold">
            THIRD PARTY SERVICES, THIRD PARTY APPLICATIONS, WEBSITES &amp;
            SERVICES:
          </p>
          <p className="mt-3">
            The Solution may include links to other websites or services
            provided by third parties, such as WhatsApp business platforms.
            These third-party services have their own privacy policies. We are
            not responsible for the privacy practices or content of these
            third-party services. If you have questions about their privacy
            policies, please contact them directly.
          </p>
          <p className="mt-3">
            We may use third-party advertising companies to serve ads when you
            visit the Solution. These companies may collect, use, and share
            information about you and your usage. We cannot control how these
            third parties collect, use, share, or secure this information.
          </p>
          <p className="mt-10 font-extrabold">ACCESS, CORRECTION, AND DELETION:</p>
          <p className="mt-3">
            We strive to keep our records updated and accurate with your latest
            information. You are responsible for ensuring that the information
            you provide is correct and updated. Deleting certain information or
            withdrawing consent may lead to the cancellation of your access to
            some services. We may not be able to process your requests for
            correction, updating, or deletion if it is not supported by valid
            documents, if data retention is required by law, or if it risks the
            privacy of other users.
          </p>
          <p className="mt-10 font-extrabold">PROCESSING OF THE INFORMATION:</p>
          <p className="mt-3">
            We and our affiliates or Third Party Service Providers may process
            personal and usage-related information collected from you for
            legitimate commercial purposes, including providing services for the
            Solution, unless you explicitly opt out. Opting out may affect your
            ability to use the Solution.
          </p>
          <p className="mt-10 font-extrabold">WAIVER OF LIABILITY:</p>
          <p className="mt-3">
            We are not liable for any indirect, incidental, consequential,
            special, or exemplary damages arising due to loss of data or use, or
            inability to access or use the Solution, including any sub-domains
            or Third Party Services.
          </p>
          <p className="mt-10 font-extrabold">QUERIES AND COMPLAINTS:</p>
          <p className="mt-3">
            We are committed to protecting your personal information. If you
            have any feedback or concerns regarding our privacy practices,
            please contact our Data Protection Officer at legal@prodoc.io.
          </p>
        </div>
      </div>
    </section>
  );
}
